services:
  postgres:
    image: postgres
    container_name: gestao_vagas_postgres
    environment:
      POSTGRES_DB: gestao_vagas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
